<?php
namespace AppBundle\Repository;

/**
 * ClothRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClothRepository extends \Doctrine\ORM\EntityRepository
{
    
}
