<?php

namespace AppBundle\Repository;

/**
 * GroupClothRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupClothRepository extends \Doctrine\ORM\EntityRepository
{
}
