<?php

namespace AppBundle\Repository;

/**
 * UnitMeasureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitMeasureRepository extends \Doctrine\ORM\EntityRepository
{
}
